[TH2-2109] Remove generation xml tags for empty messages.
th2-net/th2-codec-xml pull request #2
Opened 2021-07-13 10:40 UTC by Ilya-Loginov-Exactpro

Add ability to create embedded messages collections.

2021-07-13 11:37 UTC, Nikita-Smirnov-Exactpro requested changes

2021-07-13 11:37 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/xml/XmlMessageStructureVisitor.kt
> +                if (generated) {
value of generated is always false

2021-07-13 11:37 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/xml/XmlMessageStructureVisitor.kt
> +                ) { generated = true }, fldStruct
Please compare message's field names and fields structure's field names instead

2021-07-13 12:27 UTC, Ilya-Loginov-Exactpro commented
Added new attribute `XmlHide`. `Embedded` - XML has a nesting level, the parsed message hasn't one. `XmlHide` - the parsed message has a nesting level, XML hasn't one.

2021-07-13 13:28 UTC, Nikita-Smirnov-Exactpro requested changes

2021-07-13 13:28 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/xml/XmlPipelineCodec.kt
> +        const val XML_HIDE_ATTRIBUTE = "XmlHide"
Rename to Virtual

2021-07-13 13:28 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/xml/XmlPipelineCodec.kt
> +         * Boolean attribute. If true fields from current message will be move to a parent message
```suggestion
         * Boolean attribute. If true fields from the current message will be moved to a parent message during decoding and packed to sub-message during encoding.
```

2021-07-13 13:28 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/xml/XmlPipelineCodec.kt
> +         * Boolean attribute. If true xml tag for current message will not created
```suggestion
         * Boolean attribute. If true fields from the current message will be packed to sub-message during decoding and moved to a parent message during encoding.
```

2021-07-13 13:29 UTC, Nikita-Smirnov-Exactpro commented on src/test/kotlin/com/exactpro/th2/codec/xml/XmlPipelineCodecTest.kt
> +    }
please add reverse tests for encode

2021-07-14 08:29 UTC, Ilya-Loginov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/xml/XmlMessageStructureVisitor.kt
> +                }
This check will be executed only when the parent and child virtual message has fields with equals names. But we can prohibit this behavior.

2021-07-14 08:40 UTC, Nikita-Smirnov-Exactpro commented on src/test/kotlin/com/exactpro/th2/codec/xml/XmlPipelineCodecTest.kt
> +            //assertEquals(expected.metadata.protocol, actual.metadata.protocol, "Not equals protocols")
Why are these lines commented?

2021-07-14 09:01 UTC, Nikita-Smirnov-Exactpro approved these changes

2021-07-14 09:29 UTC, merged