[TS-682] Fixed encoding and decoding virtual messages collections and their fields.
th2-net/th2-codec-xml pull request #3
Opened 2021-07-15 17:01 UTC by Ilya-Loginov-Exactpro

2021-07-15 17:50 UTC, Nikita-Smirnov-Exactpro requested changes

2021-07-15 17:50 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/xml/XmlPipelineCodec.kt
> +                message[fieldName] = virtualMessage
Let's implement the logic
1) create a message
2) check does the current message contain the current node
2-yes.1) check if the current message structure collection
2-yes.1-yes) store current message, create new, go to 2-no.1
2-yes.1-no) throw the exception "... the node has duplicated field ..."
2-no.1) put field, go to the next initiation

2021-07-20 08:25 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/xml/XmlMessageStructureVisitor.kt
> +                if (valueNode == null || valueNode.getText() != fieldValue) {
Maybe add else for this case

2021-07-20 08:25 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/xml/XmlMessageStructureVisitor.kt
> +            else node.findOrAddNode(xmlTagName, document)
```        
val newNode = when {
    fldStruct.isVirtual() -> node
    isCollection || multiplyParent -> node.addNode(xmlTagName, document)
    else -> node.findOrAddNode(xmlTagName, document)
}
```

2021-07-20 08:49 UTC, Ilya-Loginov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/xml/XmlMessageStructureVisitor.kt
> +                if (valueNode == null || valueNode.getText() != fieldValue) {
Why? In this method, we encode a single string field. Fields in the virtual collection messages need this condition. If we found a node with an equals value we should not create a new node. We can change `valueNode.getText() != fieldValue` to `multiplyParent`.

2021-07-20 09:06 UTC, Nikita-Smirnov-Exactpro approved these changes

2021-07-20 09:08 UTC, merged